FROM python:3.10.20-slim

WORKDIR /app
COPY . .

RUN pip install flask opencv-python
RUN apt-get update && apt-get install -y \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libxcb1 \
    libgl1

CMD ["python", "main.py"]
