FROM python:3.10.20-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libglib2.0-0
    # libsm6 \
    # libxext6 \
    # libxrender1 \
    # libxcb1 \
    # libgl1
COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "main.py"]
